a= float(input("enter first number:"))
b= float (input("enter second number:" ))
print("the value of",a,"+",b,"is:",a+b)
print("the value of",a,"-",b,"is:",a-b)
print("the value of",a,"*",b,"is:",a*b)
print("the value of",a,"/",b,"is:",a/b)
print("the value of",a,"//",b,"is:",a//b)
print("the value of",a,"%",b,"is:",a%b)
print("the value of",a,"**",b,"is:",a**b)
